server:
  port: 8888
  servlet:
    context-path: /

spring:
  application:
    name: ai-chat-backend
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Logging Configuration
logging:
  level:
    com.aichat: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# MCP Configuration
mcp:
  server:
    url: http://localhost:3001
    timeout: 30000
  tools:
    filesystem:
      enabled: true
      root-path: /tmp
    web-search:
      enabled: true
    code-execution:
      enabled: true
      timeout: 10000
    database:
      enabled: true

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3002
    - http://127.0.0.1:3000
    - http://127.0.0.1:3002
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
